version: '3.8'

services:

  boletines-oficiales:
    ports:
      - "8083:8083"
    build:
      context: ./BACK-boletines-oficiales
    container_name: boletines-oficiales-service
    networks:
      - boletines-oficiales-network
    restart: "no"
    environment:
      - PORT=8083
      - DB_HOST=postgresql-host
      - DB_PORT=5432
      - DB_DATABASE=boletinesoficiales
      - DB_USERNAME=postgres
      - DB_PASSWORD=Password12345
    depends_on:
      postgresql:
        condition: service_healthy

  nlp-boletines-oficiales:
    ports:
      - "8084:8084"
    build:
      context: ./NLP-boletines-oficiales
    container_name: nlp-boletines-oficiales-service
    networks:
      - boletines-oficiales-network
    restart: "no"
    environment:
      - OPENAI_API_KEY=drios_api_key

  postgresql:
    container_name: postgresql-host
    build:
      context: .
      dockerfile: data/Dockerfile
    restart: "no"
    environment:
      - POSTGRES_DB=boletinesoficiales
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password12345
    ports:
      - "5432:5432"
    networks:
      - boletines-oficiales-network

networks:
  boletines-oficiales-network:
    driver: bridge
