version: '3.8'

services:

  boletines-oficiales:
    ports:
      - "8083:8083"
    build:
      context: ./BACK-boletines-oficiales
    container_name: boletines-oficiales
    networks:
      - boletines-oficiales-network
    restart: "no"
    environment:
      - PORT=8083
      - DB_HOST=postgresql-host
      - DB_PORT=5432
      - DB_DATABASE=boletinesoficiales
      - DB_USERNAME=postgres
      - DB_PASSWORD=Password12345
    depends_on:
      postgresql-host:
        condition: service_healthy

  nlp-boletines-oficiales:
    ports:
      - "8084:8080"
    build:
      context: .
      dockerfile: ./NLP-boletines-oficiales/Dockerfile
    container_name: nlp-boletines-oficiales
    networks:
      - boletines-oficiales-network
    restart: "no"
    environment:
      - OPENAI_API_KEY=drios_api_key
    volumes:
      - ./NLP-boletines-oficiales:/app/NLP-boletines-oficiales

  postgresql-host:
    container_name: postgresql-host
    build:
      context: .
      dockerfile: data/Dockerfile
    restart: "no"
    environment:
      - POSTGRES_DB=boletinesoficiales
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password12345
    ports:
      - "5432:5432"
    networks:
      - boletines-oficiales-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/init-sql.sql:/docker-entrypoint-initdb.d/init-sql.sql
networks:
  boletines-oficiales-network:
    driver: bridge
volumes:
  db_data: