# Dockerfile para Nginx
FROM nginx:alpine

# Copiar archivos de configuración
COPY Nginx-config/config/nginx.conf /etc/nginx/conf.d/default.conf

# Copiar archivos estáticos desde la aplicación NLP
#COPY NLP-boletines-oficiales/src/templates/ etc/nginx/html/api/
